### ISSUE TITLE
Can't find ../config

### ISSUE THREAD

**Issue by regis456** [DustinJSilk/reactive-trader#14]
If you're submitting a feature request you can delete everything here and just describe the feature.

For issues, make sure you've checked these off before submitting the issue:

- [ ] You are running the latest version of Gekko and Reactive Trader
- [ ] You are running Gekko with Postgres or Mongodb and not SQLite

Gekko is setup and works when you test it:
- [ ] From Gekkos UI
- [ ] Straight through the command line

You've tested doing all of these with Gekkos UI **and** straight through the command line:
- [ ] Importing data
- [ ] Backtesting
- [x ] Paper and / or live trading

## The issue

I heard rumors of a plugin and it's been a year since you started development and I was wondering if it ever got finished? I tried to edit the index.js to the path of my gekko config file but it still gives me the error for not being able to find the module. Please help!

## Logs

module.js:550
    throw err;
    ^

Error: Cannot find module '../config'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/gekko/reactive-trader/index.js:3:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

Error:

Info:

Status:
Sorry couldn't find the log files. RIP noob status.

**Comment by regis456** [comment]
Does gekko still use sql? How do i change to one of the other database types if it doesn't. I am at a complete loss right now and would really appreciate some guidance!
