### ISSUE TITLE
Error on npm run trade.

### ISSUE THREAD

**Issue by tylerjheslop** [DustinJSilk/reactive-trader#2]
Ran npm install, npm run trade. Opened a 2nd terminal window, npm run build, npm run front end.

```
toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: 'Internal Server Error' } }
(node:2492) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trades' of undefined
    at Genetic.optimize (/Users/tyla/Blackhat/selfhosted/gekko/reactive-trader/components/strategyfinder.js:110:11)
    at /Users/tyla/Blackhat/selfhosted/gekko/reactive-trader/node_modules/genetic-js/lib/genetic.js:135:18
    at Array.sort (native)
    at /Users/tyla/Blackhat/selfhosted/gekko/reactive-trader/node_modules/genetic-js/lib/genetic.js:134:16
    at <anonymous>
(node:2492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by DustinJSilk** [comment]
Looks like the candles aren't getting saved / retrieved which means your database might not be setup properly.
If you followed the instructions under the Postgresql setup then you will also need to add a 'database'  to the postgresql part of the config.js and make sure it does exist. (Ive added that to the readme)

**Comment by tylerjheslop** [comment]
That sounds like something I neglected to do. I'll reread the docs and update later today, thank you.
