### ISSUE TITLE
[BUG] Live mode does not work

### ISSUE THREAD

**Issue by xteejx** [DustinJSilk/reactive-trader#7]
Not sure if it has been implemented yet, so apologies if I'm a little quick off the mark.
I've tried different permutations of paper/live in both reactive-trader's config and gekko's (including turning all of gekko's to false), and while paper trading seems to work, live does not.
My config is set up correctly to work in cli/terminal in live trading, so don't think it's that.

The problem appears to be the inability to flick between paper trading for backtesting (config.paperTrader = true) and config.trader = false/true when going live.

config.performanceAnalyzer seems to kill everything if it's on and I try to test it. Not sure what's happening there (or what it's for).

Hope that helps.

**Comment by DustinJSilk** [comment]
Could you give the latest update a go.  The important bits are:

```
data.paperTrader.enabled = config.paperTrader;
data.trader.enabled = config.liveTrader;
```

**Comment by xteejx** [comment]
Absolutely!

**Comment by xteejx** [comment]
Okay, got a result.
Papertrader works perfectly, and liveTrader does indeed set the correct parameter in the config file, however I get this:
```
2018-01-28 21:12:43 (DEBUG):	Processing 87 new trades. From 2018-01-28 20:29:15 UTC to 2018-01-28 21:05:32 UTC. (36 minutes)

2018-01-28 21:12:47 (DEBUG):	No new trades.
2018-01-28 21:12:47 (INFO):	Done importing!

Testing stratego_smaxv10_SL
/home/roy/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:133
  let balance = this.current.currency + this.price * this.current.asset;
                             ^

TypeError: Cannot read property 'currency' of undefined
    at PerformanceAnalyzer.calculateReportStatistics (/home/roy/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:133:30)
    at PerformanceAnalyzer.bound [as calculateReportStatistics] (/home/roy/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at PerformanceAnalyzer.finalize (/home/roy/gekko/plugins/performanceAnalyzer/performanceAnalyzer.js:170:23)
    at PerformanceAnalyzer.bound [as finalize] (/home/roy/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /home/roy/gekko/core/gekkoStream.js:46:25
    at /home/roy/gekko/node_modules/async/dist/async.js:3205:16
    at replenish (/home/roy/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/home/roy/gekko/node_modules/async/dist/async.js:1015:17)
    at /home/roy/gekko/node_modules/async/dist/async.js:988:16
    at /home/roy/gekko/core/gekkoStream.js:47:12


  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/roy/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```

I believe it may be that gekko expects to be in paperTrader mode during backtesting (where it has currency/asset pair to look at), and then to flick over to live mode *after* the backtesting has completed (with the GA-amended strat parameters)

**Comment by DustinJSilk** [comment]
OKay im getting the same error. Ill investigate and submit a patch

**Comment by DustinJSilk** [comment]
Alright how about giving that latest commit a whirl.

**Comment by xteejx** [comment]
I think the issue is now that while a config is built correctly, it must be changed after import for the backtesting back to paper trading, or not changed at all to live until *after* import and backtesting are complete.
So, if live is selected, keep it as paper trading until import and GA is completed, then reinitialise the config to change it to live trader: true.

**Comment by xteejx** [comment]
Pretty sure this can be closed now since latest commits. There is a bug with kraken import, though that's unrelated to this so closing my report.
