### ISSUE TITLE
[BUG] Second round fails with 500 server error

### ISSUE THREAD

**Issue by xteejx** [DustinJSilk/reactive-trader#8]
Everything goes well on the first run, until the second evolution when it hits the below error.
I'm wondering if it's something to do with dateranges being too close together, or there not being enough data up to moment() from the exchange.
Taking 5 minutes off the endTime for every import and backtest might resolve this.

Actually, looking at the last part of the request there is
```
"importer":{"daterange":{"from":"2017-11-01 00:00:00"}},"I understand that Gekko only automates MY OWN trading strategies" .........
```
not sure if that's relevant too?

```
out 2018-01-28 19:51:05 (INFO):	We have new trading advice!

out 2018-01-28 19:51:05 (INFO):		 Position: short

out 2018-01-28 19:51:05 (INFO):		 Market price: 66.707

out 2018-01-28 19:51:05 (INFO):		 Based on market time: 2018-01-28 19:50:00


out 2018-01-28 19:51:05 (INFO):	(PROFIT REPORT) original simulated balance:	 100.00000000 EUR

out 2018-01-28 19:51:05 (INFO):	(PROFIT REPORT) current simulated balance:	 100.15827655 EUR

out 2018-01-28 19:51:05 (INFO):	(PROFIT REPORT) simulated profit:		 0.15827655 EUR (0.15827655%)

out 2018-01-28 19:51:05 (INFO):	(ROUNDTRIP) entry date (UTC)  	exit date (UTC)  	exposed duration	P&L 	profit

out 2018-01-28 19:51:05 (INFO):	(ROUNDTRIP) 2018-01-28 19:29	2018-01-28 19:44	15 minutes      	0.21	0.21

Testing stratego_smaxv10_SL


  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/roy/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)



Backtest failed:  { StatusCodeError: 500 - "Internal Server Error"
    at new StatusCodeError (/home/roy/gekko/reactive-trader/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/roy/gekko/reactive-trader/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/roy/gekko/reactive-trader/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/roy/gekko/reactive-trader/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/roy/gekko/reactive-trader/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/roy/gekko/reactive-trader/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  name: 'StatusCodeError',
  statusCode: 500,
  message: '500 - "Internal Server Error"',
  error: 'Internal Server Error',
  options: 
   { method: 'POST',
     uri: 'http://127.0.0.1:3000/api/backtest',
     body: { gekkoConfig: [Object], data: [Object] },
     json: true,
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [BufferList],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: 
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 4487,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 39557,
        [Symbol(bytesRead)]: 176 },
     connection: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 4487,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 39557,
        [Symbol(bytesRead)]: 176 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { 'content-type': 'text/plain; charset=utf-8',
        'content-length': '21',
        date: 'Sun, 28 Jan 2018 20:24:45 GMT',
        connection: 'close' },
     rawHeaders: 
      [ 'Content-Type',
        'text/plain; charset=utf-8',
        'Content-Length',
        '21',
        'Date',
        'Sun, 28 Jan 2018 20:24:45 GMT',
        'Connection',
        'close' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 500,
     statusMessage: 'Internal Server Error',
     client: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 4487,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [ClientRequest],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 39557,
        [Symbol(bytesRead)]: 176 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header: 'POST /api/backtest HTTP/1.1\r\nhost: 127.0.0.1:3000\r\naccept: application/json\r\ncontent-type: application/json\r\ncontent-length: 4335\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/api/backtest',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     request: 
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        method: 'POST',
        uri: [Url],
        body: '{"gekkoConfig":{"debug":false,"watch":{"exchange":"kraken","currency":"EUR","asset":"REP"},"tradingAdvisor":{"enabled":true,"method":"stratego_smaxv10_SL","candleSize":4,"historySize":20,"adapter":"postgresql"},"DEMA":{"short":10,"long":21,"thresholds":{"down":-0.025,"up":0.025}},"MACD":{"short":10,"long":21,"signal":9,"thresholds":{"down":-0.025,"up":0.025,"persistence":1}},"PPO":{"short":12,"long":26,"signal":9,"thresholds":{"down":-0.025,"up":0.025,"persistence":2}},"varPPO":{"momentum":"TSI","thresholds":{"weightLow":120,"weightHigh":-120,"persistence":0}},"RSI":{"interval":14,"thresholds":{"low":30,"high":70,"persistence":1}},"TSI":{"short":13,"long":25,"thresholds":{"low":-25,"high":25,"persistence":1}},"UO":{"first":{"weight":4,"period":7},"second":{"weight":2,"period":14},"third":{"weight":1,"period":28},"thresholds":{"low":30,"high":70,"persistence":1}},"CCI":{"constant":0.015,"history":90,"thresholds":{"up":100,"down":-100,"persistence":0}},"StochRSI":{"interval":3,"thresholds":{"low":20,"high":80,"persistence":3}},"custom":{"my_custom_setting":10},"talib-macd":{"parameters":{"optInFastPeriod":10,"optInSlowPeriod":21,"optInSignalPeriod":9},"thresholds":{"down":-0.025,"up":0.025}},"paperTrader":{"enabled":true,"reportInCurrency":true,"simulationBalance":{"asset":0,"currency":100},"feeMaker":0,"feeTaker":0,"feeUsing":"maker","slippage":0.05},"performanceAnalyzer":{"enabled":true,"riskFreeReturn":5},"trader":{"enabled":false,"key":"xxxohnoyoudontxxx","secret":"xxxxitsasecretdonttryuploadingthisxxxx","username":"","passphrase":"","orderUpdateDelay":1},"adviceLogger":{"enabled":true,"muteSoft":true},"pushover":{"enabled":false,"sendPushoverOnStart":false,"muteSoft":true,"tag":"[GEKKO]","key":"","user":""},"mailer":{"enabled":false,"sendMailOnStart":true,"email":"","muteSoft":true,"password":"","tag":"[GEKKO] ","server":"smtp.gmail.com","smtpauth":true,"user":"","from":"","to":"","ssl":true,"port":""},"pushbullet":{"enabled":false,"sendMessageOnStart":true,"muteSoft":true,"key":"xxx","email":"jon_snow@westeros.org","tag":"[GEKKO]"},"kodi":{"host":"http://ip-or-hostname:8080/jsonrpc","enabled":false,"sendMessageOnStart":true},"ircbot":{"enabled":true,"emitUpdates":true,"muteSoft":true,"channel":"#mygekko-1234","server":"irc.freenode.net","botName":"BottyMcBotFace"},"telegrambot":{"enabled":false,"emitUpdates":false,"token":"YOUR_TELEGRAM_BOT_TOKEN","botName":"gekkobot"},"twitter":{"enabled":false,"sendMessageOnStart":false,"muteSoft":false,"tag":"[GEKKO]","consumer_key":"","consumer_secret":"","access_token_key":"","access_token_secret":""},"xmppbot":{"enabled":false,"emitUpdates":false,"client_id":"jabber_id","client_pwd":"jabber_pw","client_host":"jabber_server","client_port":5222,"status_msg":"I\'m online","receiver":"jabber_id_for_updates"},"campfire":{"enabled":false,"emitUpdates":false,"nickname":"Gordon","roomId":null,"apiKey":"","account":""},"redisBeacon":{"enabled":false,"port":6379,"host":"127.0.0.1","channelPrefix":"","broadcast":["candle"]},"slack":{"enabled":false,"token":"","sendMessageOnStart":true,"muteSoft":true,"channel":""},"ifttt":{"enabled":false,"eventName":"gekko","makerKey":"","muteSoft":true,"sendMessageOnStart":true},"candleWriter":{"enabled":true},"adviceWriter":{"enabled":true,"muteSoft":false},"adapter":"postgresql","sqlite":{"path":"plugins/sqlite","dataDirectory":"history","version":0.1,"journalMode":"WAL","dependencies":[]},"postgresql":{"path":"plugins/postgresql","version":0.1,"connectionString":"postgres://postgres:xxxanotherpasswordxxx@localhost:5432","database":null,"schema":"public","dependencies":[{"module":"pg","version":"6.1.0"}]},"mongodb":{"path":"plugins/mongodb","version":0.1,"connectionString":"mongodb://mongodb/gekko","dependencies":[{"module":"mongojs","version":"2.4.0"}]},"backtest":{"daterange":{"from":"2018-01-25 20:24:35","to":"2018-01-28 20:24:35"}},"importer":{"daterange":{"from":"2017-11-01 00:00:00"}},"I understand that Gekko only automates MY OWN trading strategies":true,"stratego_smaxv10_SL":{"candleSize":4,"historySize":20,"thresholds":{"stoploss":"0.9970","stophistory":20,"volhistory":20,"volvar":"3.6814"}}},"data":{"candleProps":["close","start"],"indicatorResults":false,"report":true,"roundtrips":false,"trades":false}}',
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Querystring],
        _auth: [Auth],
        _oauth: [OAuth],
        _multipart: [Multipart],
        _redirect: [Redirect],
        _tunnel: [Tunnel],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Promise],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        headers: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        proxy: null,
        tunnel: false,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: '3000',
        host: '127.0.0.1',
        path: '/api/backtest',
        _json: true,
        httpModule: [Object],
        agentClass: [Function],
        agent: [Agent],
        _started: true,
        href: 'http://127.0.0.1:3000/api/backtest',
        req: [ClientRequest],
        ntick: true,
        response: [Circular],
        originalHost: '127.0.0.1:3000',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: 'Internal Server Error' } }

  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/roy/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)


  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/roy/gekko/node_modules/koa/lib/context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

.............etc
```

**Comment by DustinJSilk** [comment]
Hmm, difficult that Gekko isnt giving more information about the 500. 
Ill try recreate this on my side.

What are your settings for `backtestRange` and `updateSettingsTime`?

Seems to work okay when `updateSettingsTime` is set to 1 (for quick testing :p )

Im also thinking it has something to do with setting the correct date ranges.

**Comment by xteejx** [comment]
Actually, I'm not so sure now. The latest commits work great with paperTrade: true but when liveTrader is set to true the error that I'm about to put into the other bug happens, so can't get to the point of testing this one.
Still likely to be a date error. Maybe moment().subtract(5, 'm') or something would fix this one?

**Comment by xteejx** [comment]
This can be closed, too. Seems to be fixed in latest commits.
